CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL DEFAULT 'none',
    password VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE files(
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL UNIQUE,
    upload_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    size INT,
    
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
